repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.0.3
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
