# Generated by Django 3.0.6 on 2020-06-12 09:10
from django.db import migrations

import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_auto_20200612_0859"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogdetailpage", name="categories",),
        migrations.AddField(
            model_name="blogdetailpage",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to="blog.BlogCategory"),
        ),
    ]
