# Generated by Django 3.0.6 on 2020-06-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_auto_20200612_0910"),
    ]

    operations = [
        migrations.RenameField(model_name="blogdetailpage", old_name="blog_image", new_name="banner_image",),
    ]
