# Generated by Django 3.0.6 on 2020-06-22 09:45
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0022_uploadedimage"),
        ("blog", "0009_auto_20200622_0926"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleBlogPage",
            fields=[
                (
                    "blogdetailpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.BlogDetailPage",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, default="", max_length=100, null=True)),
                (
                    "intro_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Best size for this image will be 1400x400",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailimages.Image",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("blog.blogdetailpage",),
        ),
    ]
