# Generated by Django 3.0.6 on 2020-06-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribers", options={"verbose_name": "Subscriber", "verbose_name_plural": "Subscribers"},
        ),
    ]
